FROM openjdk:11

COPY . /spring
WORKDIR /spring

RUN ./gradlew

ENV GOOGLE_CLIENT_ID ''
ENV GOOGLE_CLIENT_SECRET ''
ENV REDIS_HOST localhost
ENV REDIS_PORT 6379
ENV REDIS_PASSWORD ''
ENV MYSQL_URL jdbc:mysql://localhost:3306/db?serverTimezone=UTC&characterEncoding=UTF-8
ENV MYSQL_USERNAME ''
ENV MYSQL_PASSWORD ''

EXPOSE 8080
STOPSIGNAL SIGINT

CMD ./gradlew build --continuous & ./gradlew bootRun
