version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./frontend:/node
    command: bash -c 'yarn && yarn start'
    tty: true
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile-dev
    ports:
      - 7000:7000
    volumes:
      - ./gateway:/node
    command: bash -c 'yarn && yarn dev'
    tty: true
