version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/node
    command: bash -c 'yarn && yarn dev'
    environment:
      - GRAPHQL_SERVER=http://gateway:7000/graphql

  backend-redis:
    image: redis:6
    ports:
      - 6379:6379

  backend-rabbitmq:
    image: rabbitmq:3
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    command: |
      bash -c '(
        while [ -z "`rabbitmqctl list_users 2>/dev/null`" ]; do sleep 1; done ;
        rabbitmqctl add_user ${RABBITMQ_USERNAME} ${RABBITMQ_PASSWORD} ;
        rabbitmqctl set_user_tags ${RABBITMQ_USERNAME} administrator ;
        rabbitmqctl set_permissions -p / ${RABBITMQ_USERNAME}  ".*" ".*" ".*" ;
      ) & rabbitmq-plugins enable rabbitmq_stomp && rabbitmq-plugins enable rabbitmq_management && rabbitmq-server'
    environment:
      - RABBITMQ_USERNAME=moomark
      - RABBITMQ_PASSWORD=moomark

  backend-auth-mysql:
    image: mysql:8.0.20
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=moomark-auth
      - MYSQL_USER=moomark
      - MYSQL_PASSWORD=1q2w3e4r
      - MYSQL_ROOT_PASSWORD=1q2w3e4r
    volumes:
      - backend-auth-mysql-volume:/var/lib/mysql

  backend-auth:
    build:
      context: ./backend/auth
      dockerfile: Dockerfile-dev
    command: bash -c './gradlew build --continuous & ./gradlew bootRun'
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./backend/auth:/spring
    depends_on:
      - backend-auth-mysql
      - backend-redis
    env_file:
      - .env
    environment:
      REDIS_HOST: backend-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ''
      MYSQL_HOSTNAME: backend-auth-mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: moomark-auth
      MYSQL_USERNAME: moomark
      MYSQL_PASSWORD: 1q2w3e4r

  backend-notification:
    build:
      context: ./backend/notification
      dockerfile: Dockerfile-dev
    command: bash -c './gradlew build --continuous & ./gradlew bootRun'
    restart: always
    ports:
      - 8081:8080
    volumes:
      - ./backend/notification:/spring
    depends_on:
      - backend-rabbitmq
    environment:
      - RABBITMQ_HOST=backend-rabbitmq
      - RABBITMQ_PORT=61613
      - RABBITMQ_USERNAME=moomark
      - RABBITMQ_PASSWORD=moomark

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile-dev
    ports:
      - 7000:7000
    volumes:
      - ./gateway:/node
    command: bash -c 'yarn && yarn dev'
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_HOST=backend-auth
      - AUTH_SERVICE_PORT=8080

volumes:
  backend-auth-mysql-volume:
