{{- if .Values.test.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-redis-deployment
  labels:
    app: moomark
    service: backend-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moomark
      service: backend-redis
  template:
    metadata:
      labels:
        app: moomark
        service: backend-redis
    spec:
      containers:
        - name: backend-redis
          image: redis:6
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: backend-redis
spec:
  selector:
    app: moomark
    service: backend-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
{{- end -}}
