apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: moomark
    service: gateway
spec:
  replicas: {{ .Values.gateway.deployment.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: moomark
      service: gateway
  template:
    metadata:
      labels:
        app: moomark
        service: gateway
    spec:
      containers:
        - name: gateway
        {{ if .Values.gateway.deployment.local.file }}
          image: blackcowmoo/moo-mark:gateway-dev
          command: ["bash", "-c", "rm -rf /node && mkdir /node && cat /node-source/source.tar.base64 | base64 --decode > /source.tar && tar xf /source.tar -C /node && cd /node/gateway && yarn && yarn dev"]
        {{ else }}
          {{ $defaultImage := printf "blackcowmoo/moo-mark:gateway-%s" .Chart.AppVersion }}
          image: {{ .Values.gateway.deployment.image | default $defaultImage | quote }}
          imagePullPolicy: Always
        {{ end }}
          ports:
            - containerPort: 7000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 7000
            initialDelaySeconds: 20
            periodSeconds: 3
    {{ if .Values.gateway.deployment.local.file }}
          volumeMounts:
          - name: gateway-source
            mountPath: /node-source
      volumes:
        - name: gateway-source
          configMap:
            name: gateway-source
    {{ end }}

{{- if .Values.gateway.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: moomark
    service: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
{{- end -}}

{{- if and .Values.gateway.istio.enabled .Values.gateway.istio.host }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.gateway.istio.host }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway
spec:
  hosts:
  - {{ .Values.gateway.istio.host }}
  gateways:
  - gateway-gateway
  http:
  - route:
    - destination:
        host: gateway
        port:
          number: 80
{{- end -}}

{{- if .Values.gateway.deployment.local.file }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-source
data:
  source.tar.base64: {{ .Files.Get .Values.gateway.deployment.local.file | b64enc }}
{{- end -}}
