 spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
              ${secrets.GOOGLE_CLIENT_ID}
            client-secret: 
              ${secrets.GOOGLE_CLIENT_SECRET}
            scope:
            - profile
            - email

  redis:
    host: localhsot
    port: 6379
    password: ${REDIS_PASSWORD}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
