name: github-actions/pull-request/backend/notification/lint
on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop

jobs:
  lint:
    name: Checkstyle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: backend-notification-java-${{ hashFiles('backend/notification/.gradle') }}
          restore-keys: backend-notification-java

      - name: Run all check
        working-directory: backend/notification
        run: ./gradlew check -x compileJava -x compileTestJava --stacktrace

      - name: Update artifact
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: notification-result
          path: backend/notification/build/reports
