name: github-actions/pull-request/backend/crawling/lint
on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop

jobs:
  lint:
    name: PyLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        working-directory: backend/crawling
        run: pip install pylint 

      - name: Run all check
        working-directory: backend/crawling
        run: pylint *.py **/*.py

