name: github-actions/pull-request/backend/chat/build
on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: backend-chat-java-${{ hashFiles('backend/chat/.gradle') }}
          restore-keys: backend-chat-java

      - name: Run build
        working-directory: backend/chat
        run: ./gradlew build -x checkstyleMain -x test --stacktrace

      - name: Run test
        working-directory: backend/chat
        run: ./gradlew test -x checkstyleMain --stacktrace

      - name: Update artifact
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: chat-result
          path: backend/chat/build/reports
