name: github-actions/pull-request/docker/lint
on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: $HOME/.docker-compose/bin
          key: docker-compose-1.26.2
          restore-keys: docker-compose-

      - name: Install docker-compose
        run: |
          if [ ! -d "$HOME/.docker-compose/bin" ]; then
            rm -rf "$HOME/.docker-compose"
            mkdir -p $HOME/.docker-compose/bin
            curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o $HOME/.docker-compose/bin/docker-compose
            chmod +x $HOME/.docker-compose/bin/docker-compose
          fi

      - name: Create environment file
        run: touch .env

      - name: Config docker-compose
        run: docker-compose config
